<?php

Error parsing included template Templates/Licenses/license-gpl30.txt
Encountered "<" at line 2, column 3 in Templates/Licenses/license-gpl30.txt.
Was expecting one of:
<STRING_LITERAL> ...
<RAW_STRING> ...
"false" ...
"true" ...
<INTEGER> ...
<DECIMAL> ...
"." ...
"+" ...
"-" ...
"!" ...
"[" ...
"(" ...
"{" ...
<ID> ...
    
